version: '3.8'

services:
  db:
    image: amazechain/postgres:14
    restart: always
#    container_name: 'postgres'
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    environment:
        POSTGRES_PASSWORD: 'postgres'
        POSTGRES_USER: 'postgres'
        #POSTGRES_HOST_AUTH_METHOD: 'trust'
#    ports:
#      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ../envs/postgresql.conf:/etc/postgresql/postgresql.conf

