version: '3.8'

services:
  frontend:
    image: amazechain/explorer_frontend:0.1.2
    pull_policy: always
    platform: linux/amd64
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file:
      -  ../envs/common-frontend.env
